# Generated by Django 5.2.4 on 2025-09-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
