# Generated by Django 5.2.4 on 2025-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_reservation_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
