import io
from datetime import datetime
from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import os
from django.conf import settings

def generate_dashboard_pdf(context, user_role):
    """Generate professional PDF report for dashboard"""
    buffer = io.BytesIO()
    
    # Create the PDF object with professional margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
        title="UniLib Dashboard Report"
    )
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Professional color scheme
    primary_color = colors.HexColor('#1E40AF')  # Professional blue
    secondary_color = colors.HexColor('#374151')  # Professional gray
    accent_color = colors.HexColor('#DC2626')  # Professional red for important items
    success_color = colors.HexColor('#059669')  # Professional green
    
    # Custom professional styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=20,
        spaceAfter=20,
        alignment=TA_CENTER,
        textColor=primary_color,
        fontName='Helvetica-Bold'
    )
    
    section_style = ParagraphStyle(
        'CustomSection',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=12,
        spaceBefore=20,
        textColor=secondary_color,
        fontName='Helvetica-Bold',
        borderPadding=5,
        leftIndent=0
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Heading3'],
        fontSize=11,
        spaceAfter=8,
        textColor=secondary_color,
        fontName='Helvetica-Bold'
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=9,
        spaceAfter=6,
        textColor=secondary_color,
        fontName='Helvetica'
    )
    
    small_style = ParagraphStyle(
        'CustomSmall',
        parent=styles['Normal'],
        fontSize=8,
        spaceAfter=4,
        textColor=colors.HexColor('#6B7280'),
        fontName='Helvetica'
    )
    
    # Header Section
    header_table_data = [
        [
            Paragraph("UNILIB", ParagraphStyle('HeaderTitle', 
                     parent=styles['Heading1'], 
                     fontSize=16, 
                     textColor=primary_color,
                     fontName='Helvetica-Bold')),
            Paragraph("Library Management System", 
                     ParagraphStyle('HeaderSub', 
                     parent=styles['Normal'], 
                     fontSize=10, 
                     textColor=secondary_color,
                     alignment=TA_RIGHT))
        ]
    ]
    
    header_table = Table(header_table_data, colWidths=[3.5*inch, 3.5*inch])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))
    
    elements.append(header_table)
    elements.append(Spacer(1, 10))
    
    # Report Title
    report_title = "Library Management Dashboard Report" if user_role in ['ADMIN', 'LIBRARIAN'] else "Personal Library Dashboard Report"
    elements.append(Paragraph(report_title, title_style))
    
    # Report metadata in a professional table
    meta_data = [
        ['Generated on:', datetime.now().strftime('%B %d, %Y at %H:%M:%S')],
        ['Generated by:', context.get('user', {}).get_full_name() if context.get('user') else 'System User'],
        ['User Role:', 'Administrator/Librarian' if user_role in ['ADMIN', 'LIBRARIAN'] else 'Student/Faculty'],
        ['Report Period:', 'Current System Status']
    ]
    
    meta_table = Table(meta_data, colWidths=[1.5*inch, 5*inch])
    meta_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F3F4F6')),
        ('TEXTCOLOR', (0, 0), (0, -1), secondary_color),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    
    elements.append(meta_table)
    elements.append(Spacer(1, 20))
    
    # Executive Summary Section
    elements.append(Paragraph("Executive Summary", section_style))
    
    if user_role in ['ADMIN', 'LIBRARIAN']:
        # Admin/Librarian Summary Statistics
        summary_data = [
            ['Key Performance Indicator', 'Value', 'Status'],
            ['Total Books in Collection', str(context.get('total_books', 0)), 'Inventory'],
            ['Total Borrow Transactions', str(context.get('total_borrows', 0)), 'Historical'],
            ['Active Borrows', str(context.get('active_borrows_count', 0)), 'Current'],
            ['Overdue Books', str(len(context.get('overdue_borrows', []))), 'Attention Required' if context.get('overdue_borrows') else 'Good'],
            ['Total Outstanding Fines', f"${context.get('total_fines', 0):.2f}", 'Revenue' if context.get('total_fines', 0) > 0 else 'None'],
            ['Total Reservations', str(context.get('total_reservations', 0)), 'Demand'],
            ['Active Reservations', str(context.get('active_reservations_count', 0)), 'Pending Fulfillment'],
        ]
    else:
        # Student/Faculty Summary Statistics
        summary_data = [
            ['Personal Library Metrics', 'Value', 'Status'],
            ['Total Books Borrowed', str(context.get('total_borrows', 0)), 'Historical'],
            ['Currently Borrowed', str(context.get('active_borrows_count', 0)), 'Active'],
            ['Pending Fines', f"${context.get('user_fines', 0):.2f}", 'Payment Due' if context.get('user_fines', 0) > 0 else 'Clear'],
            ['Total Reservations', str(context.get('total_reservations', 0)), 'Historical'],
            ['Active Reservations', str(context.get('active_reservations_count', 0)), 'Waiting'],
        ]
    
    summary_table = Table(summary_data, colWidths=[2.5*inch, 1.2*inch, 1.8*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), primary_color),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#FFFFFF')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    
    elements.append(summary_table)
    elements.append(Spacer(1, 20))
    
    # Detailed Sections based on user role
    if user_role in ['ADMIN', 'LIBRARIAN']:
        # Recent Borrows Section
        if context.get('recent_borrows'):
            elements.append(Paragraph("Recent Borrow Transactions", section_style))
            borrows_data = [['Book Title', 'Borrower', 'Issue Date', 'Due Date', 'Status']]
            for borrow in context['recent_borrows'][:8]:  # Increased limit for better coverage
                status = "Overdue" if borrow.is_overdue and not borrow.is_returned else "Active" if not borrow.is_returned else "Returned"
                borrows_data.append([
                    borrow.book.title[:35] + '...' if len(borrow.book.title) > 35 else borrow.book.title,
                    borrow.user.get_full_name()[:20],
                    borrow.issue_date.strftime('%m/%d/%Y'),
                    borrow.due_date.strftime('%m/%d/%Y'),
                    status
                ])
            
            borrows_table = Table(borrows_data, colWidths=[1.8*inch, 1.2*inch, 0.8*inch, 0.8*inch, 0.8*inch])
            borrows_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(borrows_table)
            elements.append(Spacer(1, 15))
        
        # Overdue Books Section
        if context.get('overdue_borrows'):
            elements.append(Paragraph("Overdue Books Requiring Attention", section_style))
            overdue_data = [['Book Title', 'Borrower', 'Due Date', 'Days Overdue', 'Contact']]
            for borrow in context['overdue_borrows'][:6]:
                overdue_data.append([
                    borrow.book.title[:35] + '...' if len(borrow.book.title) > 35 else borrow.book.title,
                    borrow.user.get_full_name()[:20],
                    borrow.due_date.strftime('%m/%d/%Y'),
                    str(borrow.overdue_days),
                    borrow.user.email[:25] + '...' if len(borrow.user.email) > 25 else borrow.user.email
                ])
            
            overdue_table = Table(overdue_data, colWidths=[1.8*inch, 1.2*inch, 0.8*inch, 0.7*inch, 1.2*inch])
            overdue_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), accent_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#FEF2F2')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#FECACA')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(overdue_table)
            elements.append(Spacer(1, 15))
        
        # Popular Books Section
        if context.get('popular_books'):
            elements.append(Paragraph("Most Popular Books", section_style))
            popular_data = [['Book Title', 'Author', 'Borrow Count', 'Availability']]
            for book in context['popular_books'][:6]:
                availability = "Available" if book.available_copies > 0 else "Checked Out"
                popular_data.append([
                    book.title[:35] + '...' if len(book.title) > 35 else book.title,
                    book.author[:25] + '...' if len(book.author) > 25 else book.author,
                    str(getattr(book, 'borrow_count', 0)),
                    availability
                ])
            
            popular_table = Table(popular_data, colWidths=[2*inch, 1.5*inch, 0.8*inch, 1*inch])
            popular_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), success_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F0FDF4')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#BBF7D0')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(popular_table)
            elements.append(Spacer(1, 15))
        
        # Recent Reservations Section
        if context.get('recent_reservations'):
            elements.append(Paragraph("Recent Book Reservations", section_style))
            reservations_data = [['Book Title', 'Reserved By', 'Reservation Date', 'Status', 'Priority']]
            for reservation in context['recent_reservations'][:6]:
                status_display = reservation.get_status_display()
                priority = "High" if reservation.status == 'AVAILABLE' else "Medium" if reservation.status == 'PENDING' else "Low"
                reservations_data.append([
                    reservation.book.title[:35] + '...' if len(reservation.book.title) > 35 else reservation.book.title,
                    reservation.user.get_full_name()[:20],
                    reservation.reservation_date.strftime('%m/%d/%Y'),
                    status_display,
                    priority
                ])
            
            reservations_table = Table(reservations_data, colWidths=[1.8*inch, 1.2*inch, 0.9*inch, 0.9*inch, 0.7*inch])
            reservations_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#7C3AED')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#FAF5FF')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#DDD6FE')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(reservations_table)
            elements.append(Spacer(1, 15))
    
    else:
        # Student/Faculty Detailed Sections
        if context.get('user_borrows'):
            elements.append(Paragraph("My Borrowing History", section_style))
            borrows_data = [['Book Title', 'Borrow Date', 'Due Date', 'Return Date', 'Status']]
            for borrow in context['user_borrows'][:8]:
                status = "Returned" if borrow.is_returned else "Overdue" if borrow.is_overdue else "Active"
                return_date = borrow.return_date.strftime('%m/%d/%Y') if borrow.is_returned else "N/A"
                borrows_data.append([
                    borrow.book.title[:40] + '...' if len(borrow.book.title) > 40 else borrow.book.title,
                    borrow.issue_date.strftime('%m/%d/%Y'),
                    borrow.due_date.strftime('%m/%d/%Y'),
                    return_date,
                    status
                ])
            
            borrows_table = Table(borrows_data, colWidths=[2.2*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch])
            borrows_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), primary_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(borrows_table)
            elements.append(Spacer(1, 15))
        
        # My Reservations Section
        if context.get('user_reservations'):
            elements.append(Paragraph("My Book Reservations", section_style))
            reservations_data = [['Book Title', 'Reservation Date', 'Status', 'Notification']]
            for reservation in context['user_reservations'][:6]:
                notified = "Yes" if reservation.notified_at else "No"
                reservations_data.append([
                    reservation.book.title[:45] + '...' if len(reservation.book.title) > 45 else reservation.book.title,
                    reservation.reservation_date.strftime('%m/%d/%Y'),
                    reservation.get_status_display(),
                    notified
                ])
            
            reservations_table = Table(reservations_data, colWidths=[2.5*inch, 1*inch, 1*inch, 0.8*inch])
            reservations_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), success_color),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F0FDF4')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#BBF7D0')),
                ('PADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(reservations_table)
    
    # Footer with professional disclaimer
    elements.append(Spacer(1, 20))
    footer_text = """
    <para alignment='center'>
    <font color='#6B7280' size=7>
    <i>This report was automatically generated by UniLib Library Management System.<br/>
    Contains confidential information. For authorized use only.<br/>
    Generated on: {generation_time}
    </i>
    </font>
    </para>
    """.format(generation_time=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
    
    elements.append(Paragraph(footer_text, styles['Normal']))
    
    # Build PDF
    doc.build(elements)
    
    # Get PDF value from buffer
    pdf = buffer.getvalue()
    buffer.close()
    
    return pdf